import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
async function load(file) { const source=await fs.readFile(new URL('../'+file,import.meta.url),'utf8'); return import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64')); }
const {onRequestPost:subscribe}=await load('functions/api/subscribe.ts');
const {onRequestGet:drip}=await load('functions/api/drip-cron.ts');
const env={BREVO_API_KEY:'test-only',DRIP_ENABLED:'true'};
const request=(body,headers={})=>new Request('https://deadhangs.com/api/subscribe',{method:'POST',headers:{'content-type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body)});
test('signup validates input and origin before contacting provider',async(t)=>{ let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;throw Error('unexpected')});for(const [body,headers,status] of [[{email:'bad'},{},400],[{email:'a@example.com'},{origin:'https://elsewhere.test'},403],['{',{},400],[{email:'a@example.com'},{'content-type':'text/plain'},415],['x'.repeat(4097),{},413]])assert.equal((await subscribe({request:request(body,headers),env})).status,status);assert.equal(calls,0);});
test('signup records consent list, preserves existing sequences and handles provider failure',async(t)=>{let payload;t.mock.method(globalThis,'fetch',async(_url,options)=>{payload=JSON.parse(options.body);return new Response('',{status:201})});assert.equal((await subscribe({request:request({email:' a@example.com '}),env})).status,200);assert.equal(payload.email,'a@example.com');assert.equal(payload.updateEnabled,false);assert.deepEqual(payload.listIds,[3]);globalThis.fetch=async()=>new Response(JSON.stringify({code:'duplicate_parameter'}),{status:400});assert.equal((await subscribe({request:request({email:'a@example.com'}),env})).status,200);globalThis.fetch=async()=>new Response('provider detail',{status:500});const failed=await subscribe({request:request({email:'a@example.com'}),env});assert.equal(failed.status,502);assert.ok(!(await failed.text()).includes('provider detail'));});
const cronRequest=(secret='test-only')=>new Request('https://deadhangs.com/api/drip-cron',{headers:{'x-cron-secret':secret}});
const contact={email:'sample+test@example.com',attributes:{SIGNUP_DATE:'2026-01-01',DRIP_LAST_SENT:'-1'}};
test('drip requires configured credentials and explicit activation',async(t)=>{t.mock.method(globalThis,'fetch',async()=>{throw Error('must not send')});assert.equal((await drip({request:cronRequest(),env:{}})).status,401);assert.equal((await drip({request:cronRequest('wrong'),env})).status,401);assert.deepEqual(await(await drip({request:cronRequest(),env:{BREVO_API_KEY:'test-only'}})).json(),{ok:true,enabled:false,sent:0});});
test('rejected email is not marked sent',async(t)=>{const calls=[];t.mock.method(globalThis,'fetch',async(url,options)=>{calls.push({url,options});return calls.length===1?Response.json({contacts:[contact]}):new Response('',{status:500})});const result=await drip({request:cronRequest(),env});assert.equal(result.status,502);assert.equal(calls.length,2);assert.equal((await result.json()).sent,0);});
test('accepted email updates the encoded contact endpoint and skips unsubscribed contacts',async(t)=>{const calls=[];t.mock.method(globalThis,'fetch',async(url,options)=>{calls.push({url,options});if(calls.length===1)return Response.json({contacts:[{...contact,emailBlacklisted:true},contact]});return new Response(null,{status:calls.length===2?201:204})});assert.equal((await(await drip({request:cronRequest(),env})).json()).sent,1);assert.equal(calls.length,3);assert.equal(calls[2].url,'https://api.brevo.com/v3/contacts/sample%2Btest%40example.com');assert.deepEqual(JSON.parse(calls[2].options.body),{attributes:{DRIP_LAST_SENT:'0'}});});
test('failed progress update explicitly requires review before retry',async(t)=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>++calls===1?Response.json({contacts:[contact]}):new Response(null,{status:calls===2?201:500}));const result=await drip({request:cronRequest(),env});assert.equal(result.status,502);assert.equal((await result.json()).reviewRequired,true);});
